{% set name = "pyannote.metrics" %}
{% set version = "3.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyannote.metrics-{{ version }}.tar.gz
  sha256: 08024255a3550e96a8e9da4f5f4af326886548480de891414567c8900920ee5c

build:
  number: 1
  noarch: python
  entry_points:
    - pyannote-metrics=pyannote.metrics.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - docopt >=0.6.2
    - matplotlib-base >=2.0.0
    - pandas >=0.19
    - pyannote.core >=4.1
    - pyannote.database >=4.0.1
    - python >={{ python_min }}
    - scikit-learn >=0.17.1
    - scipy >=1.1.0
    - sympy >=1.1
    - tabulate >=0.7.7

about:
  home: https://pyannote.github.io/pyannote-metrics
  summary: a toolkit for reproducible evaluation, diagnostic, and error analysis of speaker diarization systems
  doc_url: https://pythonhosted.org/pyannote.metrics/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
